// One-off image optimizer for Albert K Studio.
// Generates sibling .webp + .avif (same dimensions) for every raster image in
// /public, plus a tiny blurred base64 LQIP, and writes a manifest the SafeImage
// component reads to emit <picture> + blur-up. Re-run after adding new images:
//
//   node scripts/optimize-images.mjs
//
// It is intentionally NOT part of `npm run build` so deploys stay simple.

import { readdir, writeFile, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = path.join(root, "public");
const manifestPath = path.join(root, "src", "data", "optimizedImages.ts");

// Skip icons/logos/social — transparency + tiny size make optimization pointless
// and a blurred LQIP looks wrong behind a transparent logo.
const SKIP = ["/logos/", "/favicon", "/apple-touch-icon", "/icons.svg", "/logo-mark"];
const RASTER = /\.(png|jpe?g)$/i;

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) files.push(...(await walk(full)));
    else files.push(full);
  }
  return files;
}

function toUrl(abs) {
  return "/" + path.relative(publicDir, abs).split(path.sep).join("/");
}

async function run() {
  const all = await walk(publicDir);
  const targets = all.filter((f) => RASTER.test(f) && !SKIP.some((s) => toUrl(f).includes(s)));

  const manifest = {};
  for (const file of targets) {
    const url = toUrl(file);
    const base = file.replace(RASTER, "");
    const img = sharp(file);
    const meta = await img.metadata();

    const webpOut = `${base}.webp`;
    const avifOut = `${base}.avif`;

    // Regenerate only when missing or older than the source.
    const srcMtime = (await stat(file)).mtimeMs;
    const fresh = async (p) => existsSync(p) && (await stat(p)).mtimeMs >= srcMtime;

    if (!(await fresh(webpOut))) {
      await sharp(file).webp({ quality: 80, effort: 5 }).toFile(webpOut);
    }
    if (!(await fresh(avifOut))) {
      await sharp(file).avif({ quality: 55, effort: 5 }).toFile(avifOut);
    }

    const lqipBuf = await sharp(file).resize(24, 24, { fit: "inside" }).blur().webp({ quality: 40 }).toBuffer();
    const lqip = `data:image/webp;base64,${lqipBuf.toString("base64")}`;

    manifest[url] = {
      webp: `${url.replace(RASTER, "")}.webp`,
      avif: `${url.replace(RASTER, "")}.avif`,
      lqip,
      w: meta.width ?? 0,
      h: meta.height ?? 0,
    };
    console.log(`✓ ${url}`);
  }

  const body = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export type OptimizedImage = { webp: string; avif: string; lqip: string; w: number; h: number };

export const optimizedImages: Record<string, OptimizedImage> = ${JSON.stringify(manifest, null, 2)};
`;
  await writeFile(manifestPath, body);
  console.log(`\nWrote ${Object.keys(manifest).length} entries → ${path.relative(root, manifestPath)}`);
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
