// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export type OptimizedImage = { webp: string; avif: string; lqip: string; w: number; h: number };

export const optimizedImages: Record<string, OptimizedImage> = {
  "/gallery/ash-blonde-waves.png": {
    "webp": "/gallery/ash-blonde-waves.webp",
    "avif": "/gallery/ash-blonde-waves.avif",
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwBACdASoTABgAPuVep02pJSOiMAwBIByJZQDA3CHgTU0Kdd0c8Het/Q8TGpZFDQAA/u1ICca8LLprE2LuO58CeN8J+C3ED7DlMnzsUnwgmvLe0rZFUDQdNOo0BBUGZ8jfXZSCAAAAAA==",
    "w": 819,
    "h": 1024
  },
  "/gallery/balayage-curls.png": {
    "webp": "/gallery/balayage-curls.webp",
    "avif": "/gallery/balayage-curls.avif",
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACQBACdASoSABgAPu1qq1EppaOiqAqpMB2JZwAAH+GFm3e+P7go0pG9DwP1DxgA/sjdTCQHtU4KwCTrU6/nQyRE0zc+Mep+pDB09s+jz/3K7M0Te5TkPhboHf3h3o++6D5mLNcK7z+kAo+2JRKW14u0PkcVQpYz3AAAAA==",
    "w": 600,
    "h": 800
  },
  "/gallery/copper-red.png": {
    "webp": "/gallery/copper-red.webp",
    "avif": "/gallery/copper-red.avif",
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBQCdASoSABgAPu1kqU2ppaOiMAgBMB2JYgCdMyGDUE9huIb9/E6a84k7fhMdtooAAP7W43SmGCJ16KHTmjGllKA/70O0uKuEiXSnQXeQO1acohciB2H3uis60oj/0bGR5FkDdc0qaVrSsRoxHKw/GALzPV1BClg/T3518/gRKcIAAAA=",
    "w": 765,
    "h": 1020
  },
  "/gallery/dimensional-blonde.png": {
    "webp": "/gallery/dimensional-blonde.webp",
    "avif": "/gallery/dimensional-blonde.avif",
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBQCdASoSABgAPu1irVAppSQisBgIATAdiWUAvsAJGwelJSE/q258309sTzE6XLzAAP6UkicvN9TqO1ncBu9st6vC5szwyOUDoL8MP/dnjfHGFARH6FnvMcR2y5Pcp2ODSbC/aIHHbAAA",
    "w": 765,
    "h": 1020
  },
  "/gallery/glamour-waves.png": {
    "webp": "/gallery/glamour-waves.webp",
    "avif": "/gallery/glamour-waves.avif",
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBQCdASoSABgAPu1iqU2ppaQiMBgMATAdiUAYZoIdMTkTbsELD654d+/MtmdfizbrkkRAAAD+9Cp0PkfhnpTURtDI2Dr2nik94iLuAjibjiGl0v10sOHSJ4PAW8aCgRZcPQKRixioVT28jxqhuxStVqzJN3bTKt7HOQwgEMjgUlaPRJ9FZGeyiQAAAA==",
    "w": 765,
    "h": 1020
  },
  "/gallery/platinum-blonde.png": {
    "webp": "/gallery/platinum-blonde.webp",
    "avif": "/gallery/platinum-blonde.avif",
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwBACdASoSABgAPu1irlAppSQisBgIATAdiWcAxNgRSjCtbTTb6JhfIOr5ZW5nhQAA/ow+tRmPwWiyteTsCD2EUlvXMS9otMtyZaR20kwRNJhsm2/mrIvsGe4SNWmEWARpJgfNs6AAAA==",
    "w": 765,
    "h": 1020
  },
  "/gallery/sleek-brunette.png": {
    "webp": "/gallery/sleek-brunette.webp",
    "avif": "/gallery/sleek-brunette.avif",
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwAwCdASoNABgAPu1iqU2ppaOiMAgBMB2JYwATwACo+yEbWFpgAAD+04FhgOHBsvLwHGZxo/suMc60H1+1pqvxnqtj32k15MT6kBUJUbNLWJ04uC4JEp2eA2MI8RZZ7SFqACNGCxVQsGMH8vd9GaIOoHAAAA==",
    "w": 574,
    "h": 1020
  },
  "/gallery/textured-lob.png": {
    "webp": "/gallery/textured-lob.webp",
    "avif": "/gallery/textured-lob.avif",
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQBACdASoYABUAPu1wr1KppiQiqAgBMB2JQBYdghrcG4K2bn2OjqbGtMAj0aBrwAD+rxAmjwD8Fv1TAS2Hg9KeuAnUK/uami5VapZZKswApIvG+FTcELcNieEjW7xi7hhf81W8+lJtq10X1tlD6HG7h/mb17gnF/ZtOAAA",
    "w": 800,
    "h": 702
  },
  "/gallery/volume-blowout.png": {
    "webp": "/gallery/volume-blowout.webp",
    "avif": "/gallery/volume-blowout.avif",
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAQBQCdASoSABgAPuVipE2pJaOiMAwBIByJZQDBkBeSC1PFilNLZTczbUfJY6A4aMwAAP53szfa0M+6qi0f8QoCjTZaBUW/7+m3YZVd81RS0IeLOWNWkD4x4MMjszlKM8uAi/6Mo04vD19pGMAOlrFqYNXy3qdK1bCRKWX2EovxTrR7d8eGQAAA",
    "w": 765,
    "h": 1020
  },
  "/hero-salon.png": {
    "webp": "/hero-salon.webp",
    "avif": "/hero-salon.avif",
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwBACdASoYABIAPu1srlCppiQiqAqpMB2JZQCo9AgOAylT694jg3uLmJdNt9gAAPcEYKR5mOmlSWVOYiZXlx/RTvZkwm5OFHgkKbzOauTjmKWVxJlb2Z98lkbDF3qw4DTIG5MyqiLXERwA",
    "w": 1024,
    "h": 768
  },
  "/team/albert-k-headshot.png": {
    "webp": "/team/albert-k-headshot.webp",
    "avif": "/team/albert-k-headshot.avif",
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAACwBQCdASoYABgAPu1mqk8ppaOiKA1RMB2JQBYj2+At10bLE51g5JFtRb+b+rPhtp6u5f97wwAAzjeUoSsgVEwRmf4S1uFHPdJ9g4IIlMa43BvVT8Gopoz+/rWC3x1GLptEVuk2dtkDTIxb1ZX/Xw1jSN51RLv+kXAf9dR2zLIAHk1rDsi3I86FgI8oVS6FGOHf2YbaBoQjzj+AqSVo2AAA",
    "w": 800,
    "h": 800
  }
};
